Fix generate_config failing when trying to create a dir with empty path
While running `tesla_ce generate_config --local --with-services --with-moodle DOMAIN`
I got an error:

```
TeSLA CE version 1.0.0
Output file: tesla-ce.cfg
Traceback (most recent call last):
--cut--
  File "--cut--/venv/lib64/python3.9/site-packages/tesla_ce/client.py", line 323, in generate_configuration
    os.makedirs(os.path.dirname(output_file))
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

In this case the variable `output_file` had a value of `tesla-ce.cfg`, which the
os.path.dirname() converts to an empty string '', causing the error.